USE BananaTest;
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (1,"676.24","Ap #754-6389 Cras Av.","Fermentum Limited","Magna Et Consulting",1);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (2,"996.53","P.O. Box 360, 4862 Leo. Rd.","Et Risus Quisque Ltd","Cras Institute",2);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (3,"68.03","P.O. Box 232, 3404 Fusce Av.","Diam At Pretium Corporation","Orci Quis Industries",3);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (4,"929.76","8512 Malesuada Av.","Nullam Ut Nisi Foundation","Primis Industries",4);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (5,"115.62","Ap #278-4517 Lacus Rd.","Vel Foundation","Erat Volutpat Nulla Industries",5);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (6,"10.21","562 Dapibus St.","Arcu Eu LLC","Per Conubia Industries",6);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (7,"654.97","700-7921 Ut Avenue","Cras Consulting","Non Sapien Corp.",7);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (8,"916.13","7446 Laoreet Road","Rutrum Fusce Company","Metus In Company",8);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (9,"47.47","9421 Tristique St.","Ultrices A Consulting","Tincidunt Neque Associates",9);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (10,"413.62","P.O. Box 661, 8670 Lectus. Road","Sed Pede Institute","Massa Vestibulum Foundation",10);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (11,"22.24","Ap #807-4605 Tellus. Rd.","Nulla Eu Neque Associates","Luctus Sit Amet Associates",11);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (12,"83.94","521-2314 Curae; St.","Bibendum LLP","Elementum Company",12);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (13,"65.59","P.O. Box 316, 1855 Ullamcorper. Avenue","Vitae Purus Industries","Et Magnis Foundation",13);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (14,"33.16","810 Tellus Rd.","Libero Corp.","Semper PC",14);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (15,"76.17","P.O. Box 149, 4849 Nascetur St.","Quisque Purus Limited","Non Cursus Associates",15);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (16,"125.07","3173 Nonummy Ave","Eu Enim Foundation","Sodales Nisi Magna Corp.",16);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (17,"687.67","P.O. Box 930, 6355 Ullamcorper. Av.","Nascetur Ridiculus Institute","Aenean Massa Corporation",17);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (18,"89.65","P.O. Box 631, 1681 Pharetra, St.","Non Cursus Non Foundation","Libero Limited",18);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (19,"99.75","Ap #137-6015 Lacus. Rd.","Mauris Rhoncus Foundation","Pellentesque LLP",19);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (20,"354.63","861-3117 Eu Av.","Pellentesque A LLP","Convallis Ligula Donec LLC",20);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (21,"56.44","272-5067 Consequat Avenue","A Company","Eu Inc.",21);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (22,"37.01","709-5743 Iaculis St.","Sed Tortor Integer Institute","Dui Nec LLP",22);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (23,"48.36","3368 Est Avenue","Risus Quis Company","Libero Proin Sed Corporation",23);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (24,"118.57","Ap #792-3736 Venenatis Rd.","Integer Incorporated","Sed Pharetra Felis Corp.",24);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (25,"39.26","Ap #649-1623 Sagittis. Avenue","Egestas Incorporated","Sagittis Placerat Cras PC",25);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (26,"61.60","Ap #304-8959 Et, St.","Sem Vitae Associates","Duis Institute",26);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (27,"63.70","P.O. Box 328, 4686 Curabitur St.","Est Limited","Ornare Limited",27);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (28,"84.60","4032 Sed Avenue","Metus Vitae Velit LLC","Velit Justo Corporation",28);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (29,"37.42","7851 Est Ave","Est Industries","Ligula Industries",29);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (30,"167.48","178-8314 Lorem St.","Tellus Sem Mollis Inc.","Tincidunt Neque Associates",30);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (31,"42.20","475-9951 Sapien, Rd.","Vulputate Mauris Inc.","Ligula Nullam Enim Consulting",31);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (32,"907.24","Ap #793-1601 Per Rd.","Fermentum Incorporated","Vulputate Dui Nec Industries",32);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (33,"454.18","Ap #347-9647 Sed Avenue","Gravida LLP","Aliquet Molestie Tellus PC",33);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (34,"43.45","953-2999 Diam Av.","Facilisis Corporation","Eu Augue Porttitor LLP",34);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (35,"77.54","Ap #858-3541 Donec Rd.","Eu Odio PC","Risus In Mi Foundation",35);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (36,"32.44","656-8085 Quis Street","Nonummy Institute","Iaculis Corp.",36);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (37,"749.31","P.O. Box 502, 4487 Non, Street","Ut Consulting","Purus Incorporated",37);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (38,"18.16","297-2593 Curae; Rd.","Diam Associates","Fermentum Corp.",38);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (39,"945.96","Ap #257-3845 Justo Road","Cursus Institute","Mauris Inc.",39);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (40,"36.23","2741 Sapien. St.","Nec Ante Corporation","Nibh Associates",40);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (41,"362.73","602-2561 Pharetra. St.","Dis Parturient Industries","Feugiat Non Corp.",41);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (42,"457.00","Ap #652-9649 Nisi Road","Ac Mattis Semper Incorporated","Ipsum Inc.",42);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (43,"82.52","1888 Mattis St.","Eu Odio Phasellus Incorporated","Mus Donec Corporation",43);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (44,"914.07","694-2597 Gravida Avenue","Arcu Eu Odio Limited","Enim Suspendisse Aliquet Ltd",44);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (45,"96.74","Ap #409-4032 Vitae Street","Non Bibendum Sed LLP","Non Massa Non Consulting",45);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (46,"346.69","1920 Lacus Ave","Adipiscing Elit LLC","Praesent Eu Nulla PC",46);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (47,"57.12","9505 Scelerisque St.","Magna Phasellus Associates","Cras Company",47);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (48,"758.06","9365 Accumsan St.","Vehicula Pellentesque Tincidunt Consulting","Egestas Foundation",48);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (49,"418.55","P.O. Box 622, 6085 Sed Street","At Nisi Cum LLC","Neque Foundation",49);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (50,"973.35","P.O. Box 953, 5022 Cum Rd.","Phasellus At Incorporated","Magna Sed Dui LLC",50);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (51,"841.57","Ap #330-2132 Iaculis St.","Pellentesque Tellus Foundation","Integer Id Magna Inc.",51);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (52,"604.34","3255 Non St.","Rhoncus Foundation","Molestie Incorporated",52);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (53,"445.97","835-8866 Urna St.","Erat Foundation","Eleifend Vitae Incorporated",53);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (54,"10.05","P.O. Box 104, 4285 Sit Rd.","At Egestas Industries","Non Nisi Aenean LLP",54);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (55,"227.26","P.O. Box 765, 6542 Mauris Rd.","Pede Suspendisse Ltd","Praesent Luctus Curabitur Industries",55);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (56,"75.06","Ap #135-6211 Imperdiet Avenue","Tortor Company","Sodales LLP",56);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (57,"164.87","988-1942 Justo Street","Non Limited","Erat Neque Consulting",57);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (58,"286.31","Ap #169-339 Lobortis St.","Libero Donec Inc.","Fringilla Industries",58);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (59,"84.58","P.O. Box 362, 5805 Neque Rd.","Egestas Corp.","Mus Aenean Eget Corporation",59);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (60,"97.60","P.O. Box 800, 9903 Pede. Rd.","Nunc Institute","Nec Urna Limited",60);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (61,"686.67","P.O. Box 356, 5873 Malesuada Av.","Est Vitae Corporation","Pede Nec Consulting",61);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (62,"366.85","P.O. Box 549, 704 Donec Road","Nonummy Corporation","Lacus Inc.",62);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (63,"114.66","1638 Cursus St.","Et Malesuada Industries","Nunc Est Consulting",63);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (64,"81.09","377-7571 Amet Rd.","Vitae Purus LLC","Blandit Viverra Ltd",64);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (65,"502.97","Ap #885-399 Augue, St.","Dui Company","Tempor Est Incorporated",65);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (66,"42.11","691-1258 Semper Avenue","Scelerisque Dui PC","Luctus Sit Incorporated",66);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (67,"21.53","3714 Arcu Rd.","Sollicitudin Adipiscing Ligula Industries","Sapien Molestie Corp.",67);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (68,"919.13","P.O. Box 569, 3736 Erat, Rd.","Lectus Foundation","Sem Egestas Blandit Associates",68);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (69,"40.81","Ap #941-8567 Aliquam Av.","Id Institute","Vestibulum Accumsan Foundation",69);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (70,"930.22","4003 Turpis St.","Eros Non Enim Company","Viverra Maecenas Iaculis Institute",70);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (71,"925.86","P.O. Box 879, 475 Nisl. Ave","Eu Consulting","Magnis Dis Parturient Institute",71);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (72,"540.62","Ap #968-6524 Phasellus St.","Lacus Ut Foundation","Nibh Aliquam Associates",72);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (73,"14.69","149-2305 Aliquam St.","Est Inc.","Est Limited",73);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (74,"80.52","3722 Risus, Road","Hendrerit Neque Inc.","Nisi A Associates",74);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (75,"97.48","8583 Nibh Av.","Quis Industries","Taciti PC",75);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (76,"54.09","4128 Risus. Avenue","Donec At Arcu Inc.","Ut Lacus Limited",76);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (77,"92.56","P.O. Box 180, 6193 Non, Ave","Netus Et Malesuada PC","Urna Associates",77);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (78,"21.93","Ap #846-8499 Turpis Road","Nunc Nulla Vulputate Inc.","Libero Morbi Limited",78);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (79,"284.57","Ap #978-5196 Laoreet Av.","Interdum Ligula Limited","Egestas Lacinia Incorporated",79);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (80,"434.41","Ap #459-975 Elit Street","Scelerisque Mollis Consulting","Vivamus Company",80);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (81,"95.12","492-4270 Ante St.","Augue Porttitor Consulting","Quis Lectus Consulting",81);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (82,"91.42","Ap #623-2609 Quam. Street","Pharetra Nibh Aliquam Inc.","Sit Inc.",82);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (83,"262.83","P.O. Box 652, 9017 Etiam Road","Lorem Eget Industries","Metus In Lorem Consulting",83);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (84,"63.87","P.O. Box 803, 4991 Penatibus St.","Magna Company","Risus Industries",84);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (85,"80.27","Ap #213-4443 Vitae Street","Maecenas Libero Ltd","Vivamus Corp.",85);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (86,"735.42","Ap #390-574 Ut Rd.","Amet Inc.","Et Associates",86);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (87,"46.35","P.O. Box 179, 1725 Pede. Avenue","Cursus Purus Nullam Corporation","Id Risus Quis Corp.",87);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (88,"780.97","1223 Sed Av.","Quam Consulting","Sem Institute",88);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (89,"307.87","971-8927 A, Road","Sollicitudin Commodo LLC","Massa Rutrum LLC",89);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (90,"72.75","9001 Scelerisque Av.","Eros PC","Massa Quisque Corporation",90);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (91,"361.71","P.O. Box 998, 8305 Montes, Avenue","Mauris Non Dui Industries","Metus Corporation",91);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (92,"50.61","Ap #426-4914 Dui, Rd.","Non Incorporated","Penatibus Et PC",92);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (93,"661.23","693-8531 Felis. Road","Curae; LLP","Dui Augue Eu Industries",93);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (94,"45.72","P.O. Box 258, 4831 Dictum. St.","Cras LLP","Diam Vel Associates",94);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (95,"35.81","P.O. Box 694, 2362 Aliquam Avenue","Lobortis Associates","Lectus Convallis Industries",95);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (96,"87.27","Ap #851-6765 Eu St.","Aliquet Metus Urna Associates","Maecenas Ornare Associates",96);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (97,"219.84","Ap #631-5034 Cubilia Avenue","Urna Et Arcu Industries","Nunc Ullamcorper Eu Corp.",97);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (98,"66.87","1636 Ridiculus Av.","Iaculis Lacus Corporation","Fusce Mollis Inc.",98);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (99,"81.29","7025 Nascetur Road","Ante Lectus Convallis LLC","Aenean Sed Pede LLC",99);
INSERT INTO projects (project_id,billing_rate,client_location,client_name,name,vendor_id) VALUES (100,"575.56","Ap #156-6954 Lobortis. Avenue","Nascetur Incorporated","Nunc Sollicitudin Commodo Inc.",100);